using System.Globalization;
using System.Net.NetworkInformation;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.RegularExpressions;

namespace SysInfo;

/// <summary>
/// Linux counterpart of <see cref="WindowsReport"/>. Data comes from sysfs/procfs (no root needed)
/// plus optional helper tools (lspci, lsusb, dmidecode, smartctl, ...) when they are installed.
/// Root unlocks RAM slot details (dmidecode) and drive health (smartctl).
/// </summary>
internal static class LinuxReport
{
    private const string Dmi = "/sys/class/dmi/id/";
    private const string CpuRoot = "/sys/devices/system/cpu/";

    private static string Tf(bool? b) => b is null ? "-" : b.Value ? "True" : "False";

    // ------------------------------------------------------------------------------------------
    //  Entry point
    // ------------------------------------------------------------------------------------------
    public static string Build(bool isPrivileged)
    {
        var md = new MarkdownWriter();

        var osr = Lx.OsRelease();
        var meminfo = Lx.Colon(Lx.Read("/proc/meminfo"));
        var cpus = ReadCpus();
        var dimm = isPrivileged ? ReadDmidecodeMemory() : null;
        var (batteries, acOnline) = ReadPower();
        string? kernel = Lx.Read("/proc/sys/kernel/osrelease");
        string arch = ArchName();

        static string? D(string file) => Lx.Tidy(Lx.Read(Dmi + file));

        string? sysVendor = D("sys_vendor");
        string? product = D("product_name") ?? Lx.Tidy(Lx.Read("/proc/device-tree/model")); // ARM boards have no DMI
        string? boardVendor = D("board_vendor");
        string? boardName = D("board_name");

        double Kb(string key) =>
            meminfo.TryGetValue(key, out var v) &&
            double.TryParse(Regex.Match(v, @"\d+").Value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var n)
                ? n * 1024 : 0;

        double memTotal = Kb("MemTotal");
        double memAvail = meminfo.ContainsKey("MemAvailable") ? Kb("MemAvailable") : Kb("MemFree") + Kb("Buffers") + Kb("Cached");
        double swapTotal = Kb("SwapTotal"), swapFree = Kb("SwapFree");

        double installed = dimm is { Modules.Count: > 0 } ? dimm.Modules.Sum(m => m.Bytes) : memTotal;
        string installedLabel = dimm is { Modules.Count: > 0 } ? "Total Installed" : "Total Installed (as seen by OS)";
        bool haveSlots = dimm is { Slots: > 0 };
        int moduleCount = dimm?.Modules.Count ?? 0;

        string chassisDesc = "-";
        if (Lx.ReadLong(Dmi + "chassis_type") is { } chassisCode)
            chassisDesc = Lookups.ChassisType.TryGetValue((int)chassisCode, out var cn) ? cn : $"Code {chassisCode}";
        bool isLaptop = Lookups.LaptopRx.IsMatch(chassisDesc) || (chassisDesc == "-" && batteries.Count > 0);

        string fwType = GetFirmwareMode();
        bool hypervisor = cpus.Count > 0 && cpus[0].Flags.Contains("hypervisor");

        // ---- Title ---------------------------------------------------------------------------
        string? titleMake = sysVendor, titleModel = product;
        if (string.IsNullOrEmpty(titleModel) || Lookups.OemJunk.IsMatch(titleModel))
        {
            titleMake = boardVendor;
            titleModel = boardName;
        }
        string titleText = $"{titleMake} {titleModel}".Trim();
        md.H1(titleText.Length > 0 ? $"System Information: {titleText}" : "System Information");
        md.Line($"_Generated by **Lotus SysInfo** on **{DateTime.Now:yyyy-MM-dd HH:mm:ss}** | .NET {Environment.Version} | Elevated: **{(isPrivileged ? "True" : "False")}**_");
        md.Line();

        // ---- Quick summary ---------------------------------------------------------------------
        md.H2("Quick Summary");
        string uptime = "-";
        if (double.TryParse(Lx.Read("/proc/uptime")?.Split(' ')[0], NumberStyles.Float, CultureInfo.InvariantCulture, out double upSec))
        {
            var u = TimeSpan.FromSeconds(upSec);
            uptime = $"{u.Days}d {u.Hours}h {u.Minutes}m";
        }
        string osName = osr.GetValueOrDefault("PRETTY_NAME") ?? RuntimeInformation.OSDescription;
        md.KV(
            ("Manufacturer", sysVendor),
            ("Model", product),
            ("Product Family", D("product_family")),
            ("System Type", isLaptop ? $"Laptop ({chassisDesc})" : chassisDesc),
            ("CPU Model", string.Join(" + ", cpus.Select(c => c.Model))),
            ("CPU Sockets", cpus.Count),
            ("CPU Cores (physical)", cpus.Sum(c => c.Cores.Count)),
            ("CPU Threads (logical)", cpus.Sum(c => c.Threads)),
            ("RAM Total", Fmt.Size(installed)),
            ("RAM Module Count", dimm is null ? "-" : moduleCount),
            ("RAM Slots Total", haveSlots ? dimm!.Slots : "-"),
            ("RAM Slots Free", haveSlots ? dimm!.Slots - moduleCount : "-"),
            ("RAM Max Supported", dimm is { MaxBytes: > 0 } ? Fmt.Size(dimm.MaxBytes) : "-"),
            ("Operating System", $"{osName} {arch} (Kernel {kernel ?? "-"})"),
            ("BIOS Version", $"{D("bios_version") ?? "-"} ({D("bios_vendor") ?? "-"})"),
            ("Uptime", uptime));

        // ---- Computer / System -----------------------------------------------------------------
        md.H2("Computer / System");
        md.KV(
            ("Manufacturer", sysVendor),
            ("Model", product),
            ("System Family", D("product_family")),
            ("SKU / Part Number", D("product_sku")),
            ("Product Name", D("product_name")),
            ("Product Version", D("product_version")),
            ("Chassis Type", chassisDesc),
            ("Chassis Manufacturer", D("chassis_vendor")),
            ("Hypervisor Present", Tf(hypervisor)));

        // ---- BIOS / UEFI -----------------------------------------------------------------------
        md.H2("BIOS / UEFI Firmware");
        string biosDate = D("bios_date") ?? "-";
        if (DateTime.TryParseExact(biosDate, new[] { "MM/dd/yyyy", "MM/dd/yy" }, CultureInfo.InvariantCulture, DateTimeStyles.None, out var bd))
            biosDate = bd.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
        md.KV(
            ("Vendor", D("bios_vendor")),
            ("Version", D("bios_version")),
            ("Release Date", biosDate),
            ("BIOS Release", D("bios_release")),
            ("Embedded Controller", D("ec_firmware_release")),
            ("Firmware Mode", fwType));

        // ---- Motherboard -----------------------------------------------------------------------
        md.H2("Motherboard");
        md.KV(
            ("Manufacturer", boardVendor),
            ("Product", boardName),
            ("Version", D("board_version")));

        // ---- Operating system ------------------------------------------------------------------
        md.H2("Operating System");
        string? desktop = Environment.GetEnvironmentVariable("XDG_CURRENT_DESKTOP")
                          ?? Environment.GetEnvironmentVariable("XDG_SESSION_DESKTOP")
                          ?? Environment.GetEnvironmentVariable("DESKTOP_SESSION");
        string swap = string.Join("; ", ReadSwaps());
        md.KV(
            ("Name", osr.GetValueOrDefault("PRETTY_NAME") ?? osr.GetValueOrDefault("NAME")),
            ("Distribution ID", osr.GetValueOrDefault("ID")),
            ("Version", osr.GetValueOrDefault("VERSION_ID") ?? osr.GetValueOrDefault("VERSION")),
            ("Codename", osr.GetValueOrDefault("VERSION_CODENAME")),
            ("Kernel", kernel),
            ("Architecture", arch),
            ("Desktop Environment", desktop),
            ("Session Type", Environment.GetEnvironmentVariable("XDG_SESSION_TYPE")),
            ("Virtualization / Container", DetectVirtualization(hypervisor)),
            ("Boot Device", ReadRootDevice()),
            ("Virtual Memory (Total)", Fmt.Size(memTotal + swapTotal)),
            ("Virtual Memory (Free)", Fmt.Size(memAvail + swapFree)),
            ("Swap", swap));

        // ---- CPU -------------------------------------------------------------------------------
        md.H2("Processor (CPU)");
        int ci = 0;
        foreach (var c in cpus)
        {
            ci++;
            if (cpus.Count > 1) md.H3($"CPU {ci}");

            string baseClock = "-";
            var bm = Regex.Match(c.Model ?? "", @"@\s*(\d+(?:\.\d+)?)\s*GHz", RegexOptions.IgnoreCase);
            if (bm.Success) baseClock = $"{bm.Groups[1].Value} GHz";

            double? maxKhz = Lx.ReadLong($"{CpuRoot}cpu{c.FirstCpu}/cpufreq/cpuinfo_max_freq");
            double? curMhz = c.Mhz.Count > 0 ? c.Mhz.Average()
                           : Lx.ReadLong($"{CpuRoot}cpu{c.FirstCpu}/cpufreq/scaling_cur_freq") / 1000.0;
            var (l1, l2, l3) = ReadCaches(c.FirstCpu);

            md.KV(
                ("Model", c.Model),
                ("Manufacturer", c.Vendor),
                ("Description", c.Description),
                ("Architecture", arch),
                ("Physical Cores", c.Cores.Count),
                ("Logical Processors (Threads)", c.Threads),
                ("Base Clock", baseClock),
                ("Max Clock (boost)", maxKhz is > 0 ? $"{Fmt.Num(maxKhz.Value / 1_000_000, "N2")} GHz" : "-"),
                ("Current Clock", curMhz is > 0 ? $"{Fmt.Num(curMhz.Value / 1000, "N2")} GHz" : "-"),
                ("L1 Cache (per core)", l1),
                ("L2 Cache", l2),
                ("L3 Cache", l3),
                ("Virtualization Extensions (VT-x / AMD-V)", Tf(c.Flags.Contains("vmx") || c.Flags.Contains("svm"))),
                ("SLAT (EPT / NPT)", Tf(c.Flags.Contains("ept") || c.Flags.Contains("npt"))),
                ("KVM Available (/dev/kvm)", Tf(File.Exists("/dev/kvm"))));
        }
        string? load = Lx.Read("/proc/loadavg");
        string? governor = Lx.Read($"{CpuRoot}cpu0/cpufreq/scaling_governor");
        md.KV(
            ("Load Average (1 / 5 / 15 min)", load is null ? null : string.Join(" / ", load.Split(' ').Take(3))),
            ("CPU Frequency Governor", governor));

        // ---- Memory ----------------------------------------------------------------------------
        md.H2("Memory (RAM)");
        md.KV(
            (installedLabel, Fmt.Size(installed)),
            ("Module Count", dimm is null ? "-" : moduleCount),
            ("Total Slots", haveSlots ? dimm!.Slots : "-"),
            ("Empty Slots", haveSlots ? dimm!.Slots - moduleCount : "-"),
            ("Max Supported", dimm is { MaxBytes: > 0 } ? Fmt.Size(dimm.MaxBytes) : "-"),
            ("Available Now", Fmt.Size(memAvail)),
            ("In Use Now", Fmt.Size(memTotal - memAvail)),
            ("Swap Total", Fmt.Size(swapTotal)),
            ("Swap Used", Fmt.Size(swapTotal - swapFree)));

        md.H3("Installed Modules");
        if (dimm is { Modules.Count: > 0 })
        {
            var ramRows = dimm.Modules
                .OrderBy(m => m.Bank ?? "", StringComparer.OrdinalIgnoreCase)
                .ThenBy(m => m.Slot ?? "", StringComparer.OrdinalIgnoreCase)
                .Select(m => new object?[]
                {
                    m.Slot, m.Bank, Fmt.Size(m.Bytes), m.Type, m.FormFactor,
                    m.RatedSpeed, m.RunningSpeed, m.Voltage, m.Maker, m.PartNumber
                });
            md.Table(new[] { "Slot", "Bank", "Capacity", "Type", "Form Factor", "Rated Speed", "Running Speed", "Voltage (cfg)", "Manufacturer", "Part Number" }, ramRows);
        }
        else
        {
            md.Line(isPrivileged
                ? "_Module details unavailable (is `dmidecode` installed? Virtual machines and some ARM boards expose no SMBIOS memory data)._"
                : "_Module details need root: run with `sudo` (requires `dmidecode`)._");
            md.Line();
        }

        // ---- Storage ---------------------------------------------------------------------------
        md.H2("Storage");
        md.H3("Physical Disks");
        md.Table(new[] { "Device", "Model", "Type", "Bus", "Size", "Health", "Firmware" }, ReadPhysicalDisks(isPrivileged));
        if (!isPrivileged)
        {
            md.Line("_Drive health needs root (`sudo`) and `smartctl` (smartmontools)._");
            md.Line();
        }

        md.H3("Logical Volumes");
        md.Table(new[] { "Mount", "Device", "Type", "File System", "Size", "Used", "Free", "% Used" }, ReadVolumes());

        // ---- Graphics --------------------------------------------------------------------------
        md.H2("Graphics (GPU)");
        md.Table(new[] { "Name", "Vendor", "Kernel Driver", "Driver Version", "Dedicated VRAM*" }, ReadGpus(kernel));
        md.Line("_*Reported for AMD and NVIDIA GPUs only; integrated GPUs share system memory._");
        md.Line();

        // ---- Displays --------------------------------------------------------------------------
        md.H2("Displays");
        md.Table(new[] { "Connector", "Manufacturer", "Model", "Product Code", "Made (Week/Year)", "Native Resolution", "Size (diagonal)" }, ReadDisplays());

        // ---- Network ---------------------------------------------------------------------------
        md.H2("Network Adapters");
        var nics = ReadNetworkAdapters();
        if (nics.Count > 0)
            md.Table(new[] { "Adapter", "Type", "Status", "Link Speed", "Driver", "Virtual" }, nics);
        else
        {
            md.Line("_None detected._");
            md.Line();
        }

        // ---- Battery & power -------------------------------------------------------------------
        md.H2("Battery & Power");
        if (batteries.Count > 0)
        {
            foreach (var b in batteries)
            {
                var rows = new List<(string, object?)>
                {
                    ("Name", b.Name),
                    ("Manufacturer", b.Maker),
                    ("Chemistry", b.Chemistry ?? "-"),
                    ("Status", b.Status),
                    ("Charge Remaining", b.Percent is null ? "-" : $"{b.Percent} %"),
                    ("Estimated Runtime", b.RuntimeMinutes is > 0 ? $"{Math.Round(b.RuntimeMinutes.Value)} min" : "-"),
                    ("Design Capacity", b.DesignMwh is > 0 ? $"{Math.Round(b.DesignMwh.Value)} mWh" : "-"),
                    ("Full Charge Capacity", b.FullMwh is > 0 ? $"{Math.Round(b.FullMwh.Value)} mWh" : "-"),
                    ("Battery Health", b.DesignMwh is > 0 && b.FullMwh is > 0 ? $"{Fmt.Num(b.FullMwh.Value / b.DesignMwh.Value * 100, "N1")} %" : "-")
                };
                if (b.Cycles is > 0) rows.Add(("Cycle Count", b.Cycles));
                md.KV(rows.ToArray());
            }
        }
        else
        {
            md.Line("_No battery detected (likely a desktop)._");
            md.Line();
        }
        md.KV(
            ("AC Adapter", acOnline is null ? "-" : acOnline.Value ? "Connected" : "Not connected"),
            ("Active Power Plan", ReadPowerProfile()));

        // ---- Audio -----------------------------------------------------------------------------
        md.H2("Audio Devices");
        md.Table(new[] { "Name", "Driver", "Codec" }, ReadAudio());

        // ---- Peripherals -----------------------------------------------------------------------
        md.H2("Peripherals");
        md.H3("Keyboards & Pointing Devices");
        md.Table(new[] { "Type", "Name" }, ReadInputDevices());

        md.H3("Connected USB Devices");
        md.Table(new[] { "Class", "Device", "ID" }, ReadUsbDevices());

        // ---- Platform security -----------------------------------------------------------------
        md.H2("Platform Security");
        var tpm = ReadTpm();
        md.KV(
            ("Secure Boot", GetSecureBootState(fwType)),
            ("TPM Present", Tf(tpm.Present)),
            ("TPM Spec Version", tpm.SpecVersion),
            ("TPM Manufacturer", tpm.Manufacturer));

        md.Line("---");
        md.Line("_End of report · Lotus SysInfo_");

        return md.ToString();
    }

    // ------------------------------------------------------------------------------------------
    //  Basics
    // ------------------------------------------------------------------------------------------
    private static string ArchName() => RuntimeInformation.OSArchitecture switch
    {
        Architecture.X64 => "x64",
        Architecture.X86 => "x86",
        Architecture.Arm64 => "ARM64",
        Architecture.Arm => "ARM",
        var other => other.ToString()
    };

    private static string GetFirmwareMode()
    {
        if (Directory.Exists("/sys/firmware/efi")) return "UEFI";
        if (Directory.Exists(Dmi.TrimEnd('/'))) return "Legacy BIOS";
        if (Directory.Exists("/proc/device-tree")) return "Device Tree (no BIOS/UEFI)";
        return "Unknown";
    }

    private static string GetSecureBootState(string firmwareMode)
    {
        // EFI variable layout: 4 bytes of attributes followed by the value byte.
        try
        {
            const string path = "/sys/firmware/efi/efivars/SecureBoot-8be4df61-93ca-11d2-aa0d-00e098032b8c";
            if (File.Exists(path))
            {
                byte[] data = File.ReadAllBytes(path);
                if (data.Length >= 5) return data[4] == 1 ? "True" : "False";
            }
        }
        catch { }

        string? sb = Lx.Run("mokutil", new[] { "--sb-state" }, 3000, requireSuccess: false);
        if (sb is not null)
        {
            if (sb.Contains("enabled", StringComparison.OrdinalIgnoreCase)) return "True";
            if (sb.Contains("disabled", StringComparison.OrdinalIgnoreCase)) return "False";
            if (sb.Contains("doesn't support", StringComparison.OrdinalIgnoreCase)) return "Not supported";
        }
        return firmwareMode == "Legacy BIOS"
            ? "Not supported (Legacy BIOS)"
            : "Unknown / not supported / needs root";
    }

    private static string DetectVirtualization(bool hypervisorFlag)
    {
        string? kernelRelease = Lx.Read("/proc/sys/kernel/osrelease");
        bool wsl = kernelRelease?.Contains("microsoft", StringComparison.OrdinalIgnoreCase) == true
                   || kernelRelease?.Contains("WSL", StringComparison.OrdinalIgnoreCase) == true;

        string? virt = Lx.Run("systemd-detect-virt", Array.Empty<string>(), 3000, requireSuccess: false)?.Trim();
        if (!string.IsNullOrEmpty(virt) && virt != "none") return wsl && virt != "wsl" ? $"{virt} (WSL)" : virt;
        if (wsl) return "wsl";
        if (File.Exists("/.dockerenv")) return "docker";
        if (virt == "none") return "None (bare metal)";
        return hypervisorFlag ? "Virtual machine (hypervisor detected)" : "None detected";
    }

    private static string? ReadRootDevice()
    {
        string? mounts = Lx.Read("/proc/mounts");
        if (mounts is null) return null;
        string? dev = null;
        foreach (string line in mounts.Split('\n'))
        {
            var p = line.Split(' ');
            if (p.Length >= 2 && p[1] == "/") dev = p[0];
        }
        return dev;
    }

    private static IEnumerable<string> ReadSwaps()
    {
        string? swaps = Lx.Read("/proc/swaps");
        if (swaps is null) yield break;
        foreach (string line in swaps.Split('\n').Skip(1)) // header
        {
            var p = line.Split(new[] { ' ', '\t' }, StringSplitOptions.RemoveEmptyEntries);
            if (p.Length >= 3 && double.TryParse(p[2], NumberStyles.Integer, CultureInfo.InvariantCulture, out double kb))
                yield return $"{p[0]} ({Math.Round(kb / 1024)} MB)";
        }
    }

    // ------------------------------------------------------------------------------------------
    //  CPU
    // ------------------------------------------------------------------------------------------
    private sealed class CpuPackage
    {
        public int Id;
        public int FirstCpu = int.MaxValue;
        public int Threads;
        public HashSet<string> Cores { get; } = new();
        public HashSet<string> Flags { get; } = new();
        public List<double> Mhz { get; } = new();
        public string? Model, Vendor, Description;
    }

    private static List<CpuPackage> ReadCpus()
    {
        var packages = new SortedDictionary<int, CpuPackage>();

        foreach (string dir in Lx.Dirs(CpuRoot, "cpu*"))
        {
            string name = Path.GetFileName(dir);
            if (!Regex.IsMatch(name, @"^cpu\d+$")) continue;
            int idx = int.Parse(name[3..], CultureInfo.InvariantCulture);
            if (Lx.Read(dir + "/online") == "0") continue; // offline thread

            int pkgId = Lx.ReadLong(dir + "/topology/physical_package_id") is >= 0 and var pid ? (int)pid : 0;
            if (!packages.TryGetValue(pkgId, out var pkg))
                packages[pkgId] = pkg = new CpuPackage { Id = pkgId };

            long? coreId = Lx.ReadLong(dir + "/topology/core_id");
            pkg.Cores.Add(coreId is null ? $"cpu{idx}" : coreId.Value.ToString(CultureInfo.InvariantCulture));
            pkg.Threads++;
            pkg.FirstCpu = Math.Min(pkg.FirstCpu, idx);
        }

        if (packages.Count == 0) // no topology info (restricted container, odd kernels)
        {
            var pkg = new CpuPackage { Id = 0, FirstCpu = 0, Threads = Environment.ProcessorCount };
            for (int i = 0; i < pkg.Threads; i++) pkg.Cores.Add($"cpu{i}");
            packages[0] = pkg;
        }

        var blocks = Lx.CpuInfoBlocks();
        string? lscpuModel = null;
        bool lscpuTried = false;

        foreach (var pkg in packages.Values)
        {
            // x86 reports "physical id"; ARM does not (single package assumed).
            var mine = blocks
                .Where(b => (b.GetValueOrDefault("physical id") ?? "0") == pkg.Id.ToString(CultureInfo.InvariantCulture))
                .ToList();
            if (mine.Count == 0) mine = blocks;
            var first = mine.Count > 0 ? mine[0] : new Dictionary<string, string>();

            pkg.Model = first.GetValueOrDefault("model name")?.Trim();
            if (string.IsNullOrEmpty(pkg.Model))
            {
                if (!lscpuTried)
                {
                    lscpuTried = true;
                    lscpuModel = Lx.Colon(Lx.Run("lscpu", Array.Empty<string>(), 4000)).GetValueOrDefault("Model name");
                }
                pkg.Model = lscpuModel ?? first.GetValueOrDefault("Hardware") ?? "-";
            }

            string? vendor = first.GetValueOrDefault("vendor_id");
            pkg.Vendor = vendor switch
            {
                "GenuineIntel" => "Intel",
                "AuthenticAMD" => "AMD",
                "HygonGenuine" => "Hygon",
                "CentaurHauls" => "VIA/Zhaoxin",
                null => first.GetValueOrDefault("CPU implementer") is { } impl ? $"ARM implementer {impl}" : null,
                _ => vendor
            };

            if (first.TryGetValue("cpu family", out var fam))
                pkg.Description = $"Family {fam} Model {first.GetValueOrDefault("model")} Stepping {first.GetValueOrDefault("stepping")}";
            else if (first.TryGetValue("CPU part", out var part))
                pkg.Description = $"ARM part {part} revision {first.GetValueOrDefault("CPU revision")}";

            string flagText = first.GetValueOrDefault("flags") ?? first.GetValueOrDefault("Features") ?? "";
            foreach (string f in flagText.Split(' ', StringSplitOptions.RemoveEmptyEntries)) pkg.Flags.Add(f);

            foreach (var b in mine)
                if (b.TryGetValue("cpu MHz", out var mhz) &&
                    double.TryParse(mhz, NumberStyles.Float, CultureInfo.InvariantCulture, out double v))
                    pkg.Mhz.Add(v);
        }

        return packages.Values.Select(p => { if (p.FirstCpu == int.MaxValue) p.FirstCpu = 0; return p; }).ToList();
    }

    private static (string? L1, string? L2, string? L3) ReadCaches(int cpu)
    {
        double l1d = 0, l1i = 0, l2 = 0, l3 = 0;
        foreach (string idx in Lx.Dirs($"{CpuRoot}cpu{cpu}/cache", "index*"))
        {
            long? level = Lx.ReadLong(idx + "/level");
            string? type = Lx.Read(idx + "/type");
            double? size = Lx.ParseSize(Lx.Read(idx + "/size"));
            if (level is null || size is null) continue;
            switch (level)
            {
                case 1 when type == "Instruction": l1i = size.Value; break;
                case 1: l1d = size.Value; break;
                case 2: l2 = size.Value; break;
                case 3: l3 = size.Value; break;
            }
        }
        string? l1 = l1d + l1i > 0 ? $"{Fmt.Size(l1d)} data + {Fmt.Size(l1i)} instruction" : null;
        return (l1, l2 > 0 ? Fmt.Size(l2) : null, l3 > 0 ? Fmt.Size(l3) : null);
    }

    // ------------------------------------------------------------------------------------------
    //  RAM modules (dmidecode, root only)
    // ------------------------------------------------------------------------------------------
    private sealed record Dimm(string? Slot, string? Bank, double Bytes, string? Type, string? FormFactor,
                               string? RatedSpeed, string? RunningSpeed, string? Voltage, string? Maker, string? PartNumber);

    private sealed record MemoryHw(List<Dimm> Modules, int Slots, double MaxBytes);

    private static MemoryHw? ReadDmidecodeMemory()
    {
        string? output = Lx.Run("dmidecode", new[] { "-t", "memory" }, 8000);
        if (output is null) return null;

        var modules = new List<Dimm>();
        int slots = 0;
        double max = 0;

        foreach (string block in Regex.Split(output.Replace("\r", ""), @"\n\s*\n"))
        {
            var f = Lx.Colon(block);

            if (Regex.IsMatch(block, @"^Physical Memory Array\s*$", RegexOptions.Multiline))
            {
                if (int.TryParse(f.GetValueOrDefault("Number Of Devices"), out int n)) slots += n;
                max += Lx.ParseSize(f.GetValueOrDefault("Maximum Capacity")) ?? 0;
            }
            else if (Regex.IsMatch(block, @"^Memory Device\s*$", RegexOptions.Multiline))
            {
                double? size = Lx.ParseSize(f.GetValueOrDefault("Size"));
                if (size is null or <= 0) continue; // "No Module Installed"

                string? rated = Speed(f.GetValueOrDefault("Speed"));
                string? cfg = Speed(f.GetValueOrDefault("Configured Memory Speed") ?? f.GetValueOrDefault("Configured Clock Speed"));
                string? volt = Lx.Tidy(f.GetValueOrDefault("Configured Voltage"));

                modules.Add(new Dimm(
                    Lx.Tidy(f.GetValueOrDefault("Locator")),
                    Lx.Tidy(f.GetValueOrDefault("Bank Locator")),
                    size.Value,
                    Lx.Tidy(f.GetValueOrDefault("Type")),
                    Lx.Tidy(f.GetValueOrDefault("Form Factor")),
                    rated,
                    cfg ?? rated,
                    volt,
                    Lx.Tidy(f.GetValueOrDefault("Manufacturer")),
                    Lx.Tidy(f.GetValueOrDefault("Part Number"))));
            }
        }

        if (modules.Count == 0 && slots == 0) return null;
        return new MemoryHw(modules, slots, max);

        static string? Speed(string? s)
        {
            var m = Regex.Match(s ?? "", @"\d+");
            return m.Success && m.Value != "0" ? $"{m.Value} MT/s" : null;
        }
    }

    // ------------------------------------------------------------------------------------------
    //  Storage
    // ------------------------------------------------------------------------------------------
    private static List<object?[]> ReadPhysicalDisks(bool privileged)
    {
        var rows = new List<object?[]>();
        var dirs = Lx.Dirs("/sys/block")
            .OrderBy(d => Path.GetFileName(d).Length)
            .ThenBy(d => d, StringComparer.Ordinal);

        foreach (string dir in dirs)
        {
            string name = Path.GetFileName(dir);
            if (Regex.IsMatch(name, @"^(loop|ram|zram|dm-|md|nbd|sr|fd)\d")) continue; // virtual / optical / floppy
            if (Regex.IsMatch(name, @"^nvme\d+c\d+n\d+$")) continue;                    // hidden multipath path nodes
            if (Regex.IsMatch(name, @"boot\d+$|rpmb$")) continue;                       // eMMC boot/RPMB partitions

            long sectors = Lx.ReadLong(dir + "/size") ?? 0; // always 512-byte units
            if (sectors <= 0) continue;

            string real = Lx.RealPath(dir) ?? dir;
            string bus = ClassifyBus(name, real);

            string? vendor = Lx.Tidy(Lx.Read(dir + "/device/vendor"));
            string? model = Lx.Tidy(Lx.Read(dir + "/device/model")) ?? Lx.Tidy(Lx.Read(dir + "/device/name"));
            if (model is not null && vendor is not null && !vendor.Equals("ATA", StringComparison.OrdinalIgnoreCase)
                && !model.StartsWith(vendor, StringComparison.OrdinalIgnoreCase))
                model = $"{vendor} {model}";
            model ??= bus.StartsWith("Virtual") ? "Virtual disk" : null;

            string type = bus.StartsWith("Virtual") ? "Virtual"
                        : bus == "SD/MMC" ? "Flash"
                        : Lx.Read(dir + "/queue/rotational") == "1" ? "HDD" : "SSD";

            string? firmware = Lx.Read(dir + "/device/firmware_rev") ?? Lx.Read(dir + "/device/rev") ?? Lx.Read(dir + "/device/fwrev");

            rows.Add(new object?[]
            {
                "/dev/" + name, model, type, bus, Fmt.Size(sectors * 512.0),
                privileged ? SmartHealth(name) : "-", firmware
            });
        }
        return rows;
    }

    private static string ClassifyBus(string name, string realPath)
    {
        if (name.StartsWith("nvme")) return "NVMe";
        if (name.StartsWith("mmcblk")) return "SD/MMC";
        if (name.StartsWith("xvd")) return "Virtual (Xen)";
        if (name.StartsWith("vd") || realPath.Contains("/virtio")) return "Virtual (virtio)";
        if (realPath.Contains("/usb")) return "USB";
        if (realPath.Contains("/ata")) return "SATA/ATA";
        if (realPath.Contains("/end_device") || realPath.Contains("/sas")) return "SAS";
        if (realPath.Contains("/session")) return "iSCSI";
        if (name.StartsWith("hd")) return "ATA";
        if (realPath.Contains("/host")) return "SCSI";
        return "-";
    }

    private static string SmartHealth(string disk)
    {
        // smartctl exits non-zero for many "interesting" conditions, so read stdout regardless of exit code.
        string? o = Lx.Run("smartctl", new[] { "-H", "/dev/" + disk }, 8000, requireSuccess: false);
        if (o is null) return "-";
        var m = Regex.Match(o, @"(?:test result|Health Status):\s*(\w+)", RegexOptions.IgnoreCase);
        if (!m.Success) return "-";
        return m.Groups[1].Value.ToUpperInvariant() switch
        {
            "PASSED" or "OK" => "Healthy",
            "FAILED" => "Unhealthy",
            _ => "-"
        };
    }

    private static List<object?[]> ReadVolumes()
    {
        var rows = new List<(string Mount, object?[] Row)>();
        string? mounts = Lx.Read("/proc/mounts");
        if (mounts is null) return new List<object?[]>();

        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (string line in mounts.Split('\n'))
        {
            var p = line.Split(' ');
            if (p.Length < 3) continue;
            string src = Unescape(p[0]), mp = Unescape(p[1]), fs = p[2];

            bool network = fs is "nfs" or "nfs4" or "cifs" or "smb3" or "smbfs" or "fuse.sshfs" or "davfs";
            bool hostShare = fs is "9p" or "virtiofs" or "drvfs";
            bool block = src.StartsWith("/dev/") && !src.StartsWith("/dev/loop");
            if (!block && !network && !hostShare) continue;

            // Bind mounts and btrfs subvolumes repeat the same device; show each device once.
            if (!seen.Add(block ? src : src + "|" + mp)) continue;

            double total, free, avail;
            try
            {
                var di = new DriveInfo(mp);
                total = di.TotalSize;
                free = di.TotalFreeSpace;
                avail = di.AvailableFreeSpace;
            }
            catch { continue; }
            if (total <= 0) continue;

            double used = total - free;
            string type = network ? "Network" : hostShare ? "Host share" : IsRemovable(src) ? "Removable" : "Local";
            rows.Add((mp, new object?[]
            {
                mp,
                block ? src : "-", // never print server names/addresses of network shares
                type, fs, Fmt.Size(total), Fmt.Size(used), Fmt.Size(avail),
                $"{Fmt.Num(used / total * 100, "N1")} %"
            }));
        }
        return rows.OrderBy(r => r.Mount, StringComparer.Ordinal).Select(r => r.Row).ToList();

        static string Unescape(string s) =>
            Regex.Replace(s, @"\\([0-7]{3})", m => ((char)Convert.ToInt32(m.Groups[1].Value, 8)).ToString());
    }

    private static bool IsRemovable(string devicePath)
    {
        try
        {
            string dev = Path.GetFileName(Lx.RealPath(devicePath) ?? devicePath);
            string? sys = Lx.RealPath($"/sys/class/block/{dev}");
            if (sys is null || !Directory.Exists(sys)) return false;
            string disk = File.Exists(sys + "/partition") ? Path.GetDirectoryName(sys)! : sys; // partition -> parent disk
            return Lx.Read(disk + "/removable") == "1";
        }
        catch { return false; }
    }

    // ------------------------------------------------------------------------------------------
    //  PCI names (GPU, NICs)
    // ------------------------------------------------------------------------------------------
    private static readonly Lazy<Dictionary<string, (string Vendor, string Device)>> PciNames = new(() =>
    {
        var d = new Dictionary<string, (string, string)>(StringComparer.OrdinalIgnoreCase);
        string? o = Lx.Run("lspci", new[] { "-mm", "-D" }, 5000);
        if (o is null) return d;
        foreach (string line in o.Split('\n'))
        {
            // 0000:00:02.0 "VGA compatible controller" "Intel Corporation" "Alder Lake-P GT2 [Iris Xe Graphics]" -r0c ...
            var m = Regex.Match(line, "^(\\S+)\\s+\"[^\"]*\"\\s+\"([^\"]*)\"\\s+\"([^\"]*)\"");
            if (m.Success) d[m.Groups[1].Value] = (m.Groups[2].Value, m.Groups[3].Value);
        }
        return d;
    });

    private static string CleanVendor(string v)
    {
        if (v.Contains("Advanced Micro Devices", StringComparison.OrdinalIgnoreCase) || v.Contains("AMD", StringComparison.Ordinal))
            return "AMD";
        return Regex.Replace(v, @"[\s,]*(Corporation|Corp\.?|Inc\.?|Ltd\.?|Co\.|Limited)\s*$", "", RegexOptions.IgnoreCase).Trim();
    }

    private static string VendorFromId(string? id) => id?.ToLowerInvariant() switch
    {
        "0x10de" => "NVIDIA",
        "0x1002" => "AMD",
        "0x8086" => "Intel",
        "0x1af4" => "Red Hat (virtio)",
        "0x15ad" => "VMware",
        "0x1234" => "QEMU/Bochs",
        "0x1414" => "Microsoft",
        "0x80ee" => "VirtualBox",
        "0x1ab8" => "Parallels",
        _ => "-"
    };

    // ------------------------------------------------------------------------------------------
    //  GPU
    // ------------------------------------------------------------------------------------------
    private static List<object?[]> ReadGpus(string? kernel)
    {
        var rows = new List<object?[]>();
        var names = PciNames.Value;
        Dictionary<string, double>? nvidiaVram = null;

        foreach (string dev in Lx.Dirs("/sys/bus/pci/devices"))
        {
            string slot = Path.GetFileName(dev);
            string? cls = Lx.Read(dev + "/class");
            if (cls is null || !cls.StartsWith("0x03")) continue; // display controllers

            string? vid = Lx.Read(dev + "/vendor"), did = Lx.Read(dev + "/device");
            string vendor, name;
            if (names.TryGetValue(slot, out var n))
            {
                vendor = CleanVendor(n.Vendor);
                var br = Regex.Match(n.Device, @"\[(.+)\]\s*$");
                name = br.Success ? br.Groups[1].Value : n.Device;
            }
            else
            {
                vendor = VendorFromId(vid);
                name = $"PCI device {vid?.Replace("0x", "")}:{did?.Replace("0x", "")}";
            }

            string? drv = Lx.LinkName(dev + "/driver");
            string? drvVersion = drv is null ? null : Lx.Read($"/sys/module/{drv}/version");
            if (drvVersion is null && drv is not null && kernel is not null) drvVersion = $"bundled with kernel {kernel}";

            // Don't wake a sleeping hybrid-graphics dGPU just to read its memory size.
            bool asleep = Lx.Read(dev + "/power/runtime_status") == "suspended";
            double? vram = null;
            if (!asleep)
            {
                if (Lx.ReadLong(dev + "/mem_info_vram_total") is > 0 and var amdBytes)
                    vram = amdBytes;
                else if (vid?.Equals("0x10de", StringComparison.OrdinalIgnoreCase) == true && drv == "nvidia")
                {
                    nvidiaVram ??= ReadNvidiaVram();
                    string tail = slot.Length >= 7 ? slot[^7..] : slot;
                    foreach (var kv in nvidiaVram)
                        if (kv.Key.EndsWith(tail, StringComparison.OrdinalIgnoreCase)) vram = kv.Value;
                }
            }

            rows.Add(new object?[] { name, vendor, drv, drvVersion, vram is > 0 ? Fmt.Size(vram) : "-" });
        }

        // Non-PCI GPUs (Raspberry Pi, Rockchip, Apple Silicon ...) only exist as DRM devices.
        foreach (string card in Lx.Dirs("/sys/class/drm", "card*"))
        {
            if (!Regex.IsMatch(Path.GetFileName(card), @"^card\d+$")) continue;
            string? real = Lx.RealPath(card + "/device");
            if (real is null || real.Contains("/pci")) continue;
            string? drv = Lx.LinkName(card + "/device/driver");
            if (drv is null) continue;
            rows.Add(new object?[] { $"{drv} (DRM device)", "-", drv, "-", "-" });
        }
        return rows;
    }

    private static Dictionary<string, double> ReadNvidiaVram()
    {
        var d = new Dictionary<string, double>(StringComparer.OrdinalIgnoreCase);
        string? o = Lx.Run("nvidia-smi", new[] { "--query-gpu=pci.bus_id,memory.total", "--format=csv,noheader,nounits" }, 6000);
        if (o is null) return d;
        foreach (string line in o.Split('\n'))
        {
            var p = line.Split(',');
            if (p.Length >= 2 && double.TryParse(p[1].Trim(), NumberStyles.Float, CultureInfo.InvariantCulture, out double mib))
                d[p[0].Trim()] = mib * 1024 * 1024;
        }
        return d;
    }

    // ------------------------------------------------------------------------------------------
    //  Displays (EDID)
    // ------------------------------------------------------------------------------------------
    private static List<object?[]> ReadDisplays()
    {
        var rows = new List<object?[]>();
        foreach (string dir in Lx.Dirs("/sys/class/drm", "card*-*"))
        {
            if (Lx.Read(dir + "/status") != "connected") continue;
            byte[]? edid = ReadBytes(dir + "/edid");
            if (edid is null || edid.Length < 128) continue;
            if (!(edid[0] == 0 && edid[1] == 0xFF && edid[7] == 0)) continue; // EDID header

            string connector = Regex.Replace(Path.GetFileName(dir), @"^card\d+-", "");

            int mfg = (edid[8] << 8) | edid[9];
            string maker = new string(new[]
            {
                (char)('A' - 1 + ((mfg >> 10) & 0x1F)),
                (char)('A' - 1 + ((mfg >> 5) & 0x1F)),
                (char)('A' - 1 + (mfg & 0x1F))
            });

            int productCode = edid[10] | (edid[11] << 8);
            int week = edid[16], year = edid[17] + 1990;
            string made = (week is 0 or 0xFF ? "-" : week.ToString(CultureInfo.InvariantCulture)) + " / " + year.ToString(CultureInfo.InvariantCulture);

            string? model = null;
            for (int o = 54; o <= 108; o += 18)
            {
                if (edid[o] == 0 && edid[o + 1] == 0 && edid[o + 2] == 0 && edid[o + 3] == 0xFC) // monitor name descriptor
                {
                    model = Encoding.ASCII.GetString(edid, o + 5, 13).Split('\n')[0].Trim();
                    break;
                }
            }

            string native = "-";
            int pixelClock10kHz = edid[54] | (edid[55] << 8);
            if (pixelClock10kHz > 0)
            {
                int hActive = edid[56] | ((edid[58] & 0xF0) << 4);
                int hBlank = edid[57] | ((edid[58] & 0x0F) << 8);
                int vActive = edid[59] | ((edid[61] & 0xF0) << 4);
                int vBlank = edid[60] | ((edid[61] & 0x0F) << 8);
                double total = (double)(hActive + hBlank) * (vActive + vBlank);
                string hz = total > 0 ? $" @ {Math.Round(pixelClock10kHz * 10000.0 / total)} Hz" : "";
                native = $"{hActive} x {vActive}{hz}";
            }

            string size = "-";
            if (edid[21] > 0 && edid[22] > 0)
            {
                double diag = Math.Sqrt(edid[21] * edid[21] + edid[22] * edid[22]) / 2.54;
                size = $"{Fmt.Num(diag, "N1")} in";
            }

            rows.Add(new object?[] { connector, maker, model, productCode.ToString("X4", CultureInfo.InvariantCulture), made, native, size });
        }
        return rows;

        static byte[]? ReadBytes(string path)
        {
            try { return File.Exists(path) ? File.ReadAllBytes(path) : null; }
            catch { return null; }
        }
    }

    // ------------------------------------------------------------------------------------------
    //  Network
    // ------------------------------------------------------------------------------------------
    private static List<object?[]> ReadNetworkAdapters()
    {
        var rows = new List<object?[]>();
        NetworkInterface[] nics;
        try { nics = NetworkInterface.GetAllNetworkInterfaces(); }
        catch { return rows; }

        var names = PciNames.Value;
        foreach (var ni in nics.Where(n => n.NetworkInterfaceType != NetworkInterfaceType.Loopback).OrderBy(n => n.Name, StringComparer.Ordinal))
        {
            string basePath = "/sys/class/net/" + ni.Name;
            string? real = Lx.RealPath(basePath);
            bool virt = real is null || real.Contains("/devices/virtual/");

            string? desc = null;
            if (!virt && Lx.RealPath(basePath + "/device") is { } devReal)
            {
                if (names.TryGetValue(Path.GetFileName(devReal), out var n))
                    desc = $"{CleanVendor(n.Vendor)} {n.Device}";
                else // USB NICs: the product string lives on the USB device, one level above the interface
                {
                    foreach (string up in new[] { devReal, Path.GetDirectoryName(devReal) ?? devReal })
                    {
                        string? prod = Lx.Read(up + "/product");
                        if (prod is null) continue;
                        string? maker = Lx.Read(up + "/manufacturer");
                        desc = maker is not null && !prod.Contains(maker, StringComparison.OrdinalIgnoreCase) ? $"{maker} {prod}" : prod;
                        break;
                    }
                }
            }

            string type = ni.NetworkInterfaceType switch
            {
                NetworkInterfaceType.Ethernet or NetworkInterfaceType.GigabitEthernet or NetworkInterfaceType.FastEthernetT => "Ethernet",
                NetworkInterfaceType.Wireless80211 => "Wi-Fi",
                NetworkInterfaceType.Tunnel => "Tunnel",
                var other => other.ToString()
            };

            string status = ni.OperationalStatus switch
            {
                OperationalStatus.Up => "Up",
                OperationalStatus.Down => "Disconnected",
                OperationalStatus.Testing => "Testing",
                OperationalStatus.Dormant => "Dormant",
                OperationalStatus.NotPresent => "Not Present",
                OperationalStatus.LowerLayerDown => "Lower Layer Down",
                _ => "Unknown"
            };

            // sysfs reports Mb/s, with -1 (or 0xFFFFFFFF on some virtual NICs) meaning "unknown" (always the case for Wi-Fi).
            double? speed = null;
            if (Lx.ReadLong(basePath + "/speed") is > 0 and < 1_000_000 and var mbps) speed = mbps * 1_000_000.0;

            rows.Add(new object?[]
            {
                desc is null ? ni.Name : $"{desc} ({ni.Name})",
                type, status, Fmt.LinkSpeed(speed),
                Lx.LinkName(basePath + "/device/driver") ?? "-",
                Tf(virt)
            });
        }
        return rows;
    }

    // ------------------------------------------------------------------------------------------
    //  Battery & power
    // ------------------------------------------------------------------------------------------
    private sealed record Battery(string Name, string? Maker, string? Chemistry, string? Status, long? Percent,
                                  double? RuntimeMinutes, double? DesignMwh, double? FullMwh, long? Cycles);

    private static (List<Battery>, bool?) ReadPower()
    {
        var list = new List<Battery>();
        bool? ac = null;

        foreach (string d in Lx.Dirs("/sys/class/power_supply"))
        {
            string? type = Lx.Read(d + "/type");
            if (type == "Mains")
            {
                if (Lx.ReadLong(d + "/online") is { } online) ac = (ac ?? false) || online == 1;
                continue;
            }
            if (type != "Battery") continue;
            if (Lx.Read(d + "/scope") == "Device") continue; // wireless mouse / headset batteries

            string? tech = Lx.Read(d + "/technology");
            string? chem = tech switch
            {
                "Li-ion" => "Lithium-ion",
                "Li-poly" => "Lithium Polymer",
                "LiFe" => "Lithium Iron Phosphate",
                "NiMH" => "Nickel Metal Hydride",
                "NiCd" => "Nickel Cadmium",
                "Unknown" => null,
                _ => tech
            };

            string? statusRaw = Lx.Read(d + "/status");
            string? status = statusRaw switch
            {
                "Charging" => "Charging",
                "Discharging" => "Discharging",
                "Full" => "Fully charged",
                "Not charging" => "On AC power (not charging)",
                _ => null
            };

            double? runtime = null;
            if (statusRaw == "Discharging")
            {
                long? energyNow = Lx.ReadLong(d + "/energy_now"), powerNow = Lx.ReadLong(d + "/power_now");
                long? chargeNow = Lx.ReadLong(d + "/charge_now"), currentNow = Lx.ReadLong(d + "/current_now");
                if (energyNow is > 0 && powerNow is > 0) runtime = energyNow.Value / (double)powerNow.Value * 60;
                else if (chargeNow is > 0 && currentNow is > 0) runtime = chargeNow.Value / (double)currentNow.Value * 60;
                if (runtime is > 100_000) runtime = null;
            }

            list.Add(new Battery(
                Lx.Tidy(Lx.Read(d + "/model_name")) ?? Path.GetFileName(d),
                Lx.Tidy(Lx.Read(d + "/manufacturer")),
                chem, status,
                Lx.ReadLong(d + "/capacity"),
                runtime,
                EnergyMwh(d, "energy_full_design", "charge_full_design"),
                EnergyMwh(d, "energy_full", "charge_full"),
                Lx.ReadLong(d + "/cycle_count")));
        }
        return (list, ac);

        // sysfs reports energy in µWh, or charge in µAh (convert with voltage: µAh * µV / 1e9 = mWh)
        static double? EnergyMwh(string dir, string energyFile, string chargeFile)
        {
            if (Lx.ReadLong($"{dir}/{energyFile}") is > 0 and var e) return e / 1000.0;
            long? charge = Lx.ReadLong($"{dir}/{chargeFile}");
            long? volt = Lx.ReadLong(dir + "/voltage_min_design") ?? Lx.ReadLong(dir + "/voltage_now");
            return charge is > 0 && volt is > 0 ? charge.Value * (double)volt.Value / 1e9 : null;
        }
    }

    private static string? ReadPowerProfile()
    {
        string? p = Lx.Run("powerprofilesctl", new[] { "get" }, 3000)?.Trim();
        if (!string.IsNullOrEmpty(p)) return p;

        var m = Regex.Match(Lx.Run("tuned-adm", new[] { "active" }, 3000) ?? "", @"Current active profile:\s*(.+)");
        return m.Success ? m.Groups[1].Value.Trim() : null;
    }

    // ------------------------------------------------------------------------------------------
    //  Audio
    // ------------------------------------------------------------------------------------------
    private static List<object?[]> ReadAudio() =>
        ParseAudio(Lx.Read("/proc/asound/cards"), id =>
        {
            var codecs = new List<string>();
            try
            {
                foreach (string file in Directory.GetFiles($"/proc/asound/card{id}", "codec#*"))
                    codecs.Add(Lx.Read(file) ?? "");
            }
            catch { }
            return codecs;
        });

    // cardsText = /proc/asound/cards, codecDumps(cardId) = contents of that card's codec#N files
    private static List<object?[]> ParseAudio(string? cardsText, Func<string, IEnumerable<string>> codecDumps)
    {
        var rows = new List<object?[]>();
        if (cardsText is null) return rows;

        foreach (string line in cardsText.Split('\n'))
        {
            //  0 [PCH            ]: HDA-Intel - HDA Intel PCH
            var m = Regex.Match(line, @"^\s*(\d+)\s+\[[^\]]*\]:\s*(\S+)\s+-\s+(.+)$");
            if (!m.Success) continue;

            var codecs = new List<string>();
            foreach (string dump in codecDumps(m.Groups[1].Value))
            {
                var cm = Regex.Match(dump, @"^Codec:\s*(.+)$", RegexOptions.Multiline);
                if (cm.Success) codecs.Add(cm.Groups[1].Value.Trim());
            }
            rows.Add(new object?[] { m.Groups[3].Value.Trim(), m.Groups[2].Value, string.Join(", ", codecs.Distinct()) });
        }
        return rows;
    }

    // ------------------------------------------------------------------------------------------
    //  Input devices & USB
    // ------------------------------------------------------------------------------------------
    private static List<object?[]> ReadInputDevices() =>
        ParseInputDevices(Lx.Read("/proc/bus/input/devices"), minor => Lx.Read($"/run/udev/data/c13:{minor}"));

    // text = /proc/bus/input/devices, udevData(minor) = /run/udev/data/c13:<minor> (null if udev has no entry)
    private static List<object?[]> ParseInputDevices(string? text, Func<int, string?> udevData)
    {
        var rows = new List<object?[]>();
        if (text is null) return rows;

        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (string block in Regex.Split(text.Replace("\r", ""), @"\n\s*\n"))
        {
            string? name = Regex.Match(block, "^N: Name=\"(.*)\"$", RegexOptions.Multiline) is { Success: true } nm ? nm.Groups[1].Value : null;
            string handlers = Regex.Match(block, @"^H: Handlers=(.*)$", RegexOptions.Multiline) is { Success: true } hm ? hm.Groups[1].Value : "";
            if (string.IsNullOrWhiteSpace(name)) continue;

            bool keyboard, pointing, touchscreen = false;

            // udev already classified every input node; use that when available.
            string? udev = null;
            var ev = Regex.Match(handlers, @"event(\d+)");
            if (ev.Success) udev = udevData(64 + int.Parse(ev.Groups[1].Value, CultureInfo.InvariantCulture));

            if (udev is not null)
            {
                keyboard = udev.Contains("ID_INPUT_KEYBOARD=1");
                pointing = udev.Contains("ID_INPUT_MOUSE=1") || udev.Contains("ID_INPUT_TOUCHPAD=1")
                        || udev.Contains("ID_INPUT_POINTINGSTICK=1") || udev.Contains("ID_INPUT_TRACKBALL=1");
                touchscreen = udev.Contains("ID_INPUT_TOUCHSCREEN=1");
            }
            else
            {
                // Fallback heuristic: keyboards advertise key-repeat (EV_REP, bit 20); mice/touchpads get a "mouse" handler.
                var evBits = Regex.Match(block, @"^B: EV=([0-9a-fA-F]+)$", RegexOptions.Multiline);
                bool rep = evBits.Success && (Convert.ToUInt64(evBits.Groups[1].Value, 16) & (1UL << 20)) != 0;
                keyboard = handlers.Contains("kbd") && rep;
                pointing = handlers.Contains("mouse");
            }

            string? type = keyboard ? "Keyboard" : pointing ? "Pointing" : touchscreen ? "Touchscreen" : null;
            if (type is not null && seen.Add(type + "|" + name))
                rows.Add(new object?[] { type, name });
        }
        return rows.OrderBy(r => (string?)r[0], StringComparer.Ordinal).ThenBy(r => (string?)r[1], StringComparer.OrdinalIgnoreCase).ToList();
    }

    private static readonly Dictionary<string, string> UsbClass = new(StringComparer.OrdinalIgnoreCase)
    {
        ["01"] = "Audio", ["02"] = "Communications", ["03"] = "HID", ["05"] = "Physical", ["06"] = "Image",
        ["07"] = "Printer", ["08"] = "Mass Storage", ["09"] = "Hub", ["0a"] = "CDC Data", ["0b"] = "Smart Card",
        ["0d"] = "Content Security", ["0e"] = "Video / Camera", ["0f"] = "Personal Healthcare", ["10"] = "Audio/Video",
        ["11"] = "Billboard", ["dc"] = "Diagnostic", ["e0"] = "Wireless / Bluetooth", ["ef"] = "Miscellaneous",
        ["fe"] = "Application Specific", ["ff"] = "Vendor Specific"
    };

    private static List<object?[]> ReadUsbDevices()
    {
        var rows = new List<(string Cls, string Name, object?[] Row)>();

        // Names from the USB ID database, used when a device exposes no product string.
        var lsusb = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        bool lsusbLoaded = false;

        foreach (string dir in Lx.Dirs("/sys/bus/usb/devices"))
        {
            string dirName = Path.GetFileName(dir);
            if (!Regex.IsMatch(dirName, @"^\d+-\d+(\.\d+)*$")) continue; // real devices only, not root hubs or interfaces

            string? vid = Lx.Read(dir + "/idVendor"), pid = Lx.Read(dir + "/idProduct");
            if (vid is null || pid is null) continue;

            string? devClass = Lx.Read(dir + "/bDeviceClass");
            if (devClass == "09") continue; // hubs

            string? maker = Lx.Tidy(Lx.Read(dir + "/manufacturer"));
            string? prod = Lx.Tidy(Lx.Read(dir + "/product"));
            string name = prod is null ? "" : maker is not null && !prod.Contains(maker, StringComparison.OrdinalIgnoreCase) ? $"{maker} {prod}" : prod;
            if (name.Length == 0)
            {
                if (!lsusbLoaded)
                {
                    lsusbLoaded = true;
                    foreach (string l in (Lx.Run("lsusb", Array.Empty<string>(), 4000) ?? "").Split('\n'))
                    {
                        var m = Regex.Match(l, @"ID ([0-9a-fA-F]{4}):([0-9a-fA-F]{4})\s*(.*)$");
                        if (m.Success) lsusb[$"{m.Groups[1].Value}:{m.Groups[2].Value}"] = m.Groups[3].Value.Trim();
                    }
                }
                name = lsusb.GetValueOrDefault($"{vid}:{pid}") ?? "Unknown USB device";
            }

            // Composite devices declare their purpose per interface.
            string cls;
            if (devClass is null or "00" or "ef")
            {
                var ifaceClasses = Lx.Dirs("/sys/bus/usb/devices", dirName + ":*")
                    .Select(i => Lx.Read(i + "/bInterfaceClass"))
                    .Where(c => c is not null)
                    .Select(c => UsbClass.GetValueOrDefault(c!, "Other"))
                    .Distinct()
                    .Take(3);
                cls = string.Join(", ", ifaceClasses);
                if (cls.Length == 0) cls = devClass is null ? "Other" : UsbClass.GetValueOrDefault(devClass, "Other");
            }
            else cls = UsbClass.GetValueOrDefault(devClass, "Other");

            rows.Add((cls, name, new object?[] { cls, name, $"{vid}:{pid}" }));
        }
        return rows.OrderBy(r => r.Cls, StringComparer.OrdinalIgnoreCase).ThenBy(r => r.Name, StringComparer.OrdinalIgnoreCase).Select(r => r.Row).ToList();
    }

    // ------------------------------------------------------------------------------------------
    //  TPM
    // ------------------------------------------------------------------------------------------
    private sealed record TpmInfo(bool Present, string SpecVersion, string Manufacturer);

    private static TpmInfo ReadTpm()
    {
        const string root = "/sys/class/tpm/tpm0";
        if (!Directory.Exists(root)) return new TpmInfo(false, "-", "-");

        string spec = "-";
        if (Lx.Read(root + "/tpm_version_major") is { } major) spec = major + ".0";
        else if (File.Exists(root + "/device/caps")) spec = "1.2"; // only TPM 1.2 exposes "caps"

        // Manufacturer is only available through the TPM itself (tpm2-tools + access to /dev/tpmrm0).
        string manufacturer = "-";
        string? props = Lx.Run("tpm2_getcap", new[] { "properties-fixed" }, 4000);
        if (props is not null)
        {
            var m = Regex.Match(props, @"TPM2_PT_MANUFACTURER:\s*\r?\n\s*raw:\s*\S+\s*\r?\n\s*value:\s*""?([^""\r\n]+)""?");
            if (m.Success) manufacturer = m.Groups[1].Value.Trim();
        }
        return new TpmInfo(true, spec, manufacturer);
    }
}
